version: '3'

services:
  dirigible:
    image: dirigible
    build: ./dirigible
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USERNAME=${DB_USER}"
      - "DIRIGIBLE_DATABASE_PROVIDER=custom"
      - "DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES=POSTGRES"
      - "DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT=POSTGRES"
      - "POSTGRES_DRIVER=org.postgresql.Driver"
      - "POSTGRES_URL=jdbc:postgresql://database:5432/${DB}"
      - "DIRIGIBLE_SCHEDULER_DATABASE_DRIVER=org.postgresql.Driver"
      - "DIRIGIBLE_SCHEDULER_DATABASE_URL=jdbc:postgresql://database:5432/${DB}"
      - "DIRIGIBLE_SCHEDULER_DATABASE_USER=${DB_USER}"
      - "DIRIGIBLE_SCHEDULER_DATABASE_PASSWORD=${DB_PASSWORD}"
      - "DIRIGIBLE_SCHEDULER_DATABASE_DELEGATE=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
    ports:
      - "8080:8080"
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      - "POSTGRES_DB=${DB}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
    volumes:
      - "./data:/var/lib/postgresql/data"
